# Generated by Django 3.0.6 on 2020-10-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_talent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
