# Generated by Django 3.1 on 2020-10-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201015_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='instagram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='twitter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
