# Generated by Django 3.1 on 2020-10-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201015_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
