# Generated by Django 3.1 on 2020-10-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201015_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='email',
            new_name='emailprofile',
        ),
        migrations.AlterField(
            model_name='talent',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
