# Generated by Django 3.1 on 2020-10-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201015_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='accounttype',
            field=models.CharField(choices=[("I'm a Talent", "I'm a Talent"), ("I'm hiring Talent", "I'm hiring Talent")], default="I'm a Talent", max_length=17),
        ),
    ]
