# Generated by Django 3.1 on 2020-10-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_talent_accounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='accounttype',
            field=models.CharField(choices=[("I'm a Talent", "I'm a Talent"), ("I'm hiring Talent", "I'm hiring Talent")], default=(("I'm a Talent", "I'm a Talent"), ("I'm hiring Talent", "I'm hiring Talent")), max_length=17),
        ),
    ]
