# Generated by Django 3.1 on 2020-10-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201016_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='sideproject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='yearend',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='yearstart',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
