# Generated by Django 3.1 on 2020-11-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201026_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
