# Generated by Django 3.1 on 2020-11-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201108_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='sideproject_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='website_employment',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='website_institution',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='current_employment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='degree_education',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='institution_education',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='position',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='position_employment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='sideproject',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='yearend',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='yearend_education',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='yearend_employment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='yearstart',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='yearstart_education',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='yearstart_employment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
