# Generated by Django 3.1 on 2020-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201109_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='mytalentstory',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
